# Generated by Django 5.2.8 on 2025-12-13 07:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPersonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Prefer not to say')], max_length=1)),
                ('height_cm', models.PositiveIntegerField(help_text='Height in centimeters')),
                ('weight_kg', models.PositiveIntegerField(help_text='Weight in kilograms')),
                ('eye_color', models.CharField(max_length=50)),
                ('hair_color', models.CharField(max_length=50)),
                ('distinguishing_features', models.TextField(blank=True, help_text='Scars, tattoos, birthmarks, etc.')),
                ('photo', models.ImageField(blank=True, upload_to='missing_persons/%Y/%m/')),
                ('last_seen_date', models.DateTimeField()),
                ('last_seen_location', models.CharField(max_length=300)),
                ('last_seen_wearing', models.TextField(help_text='Description of clothing')),
                ('circumstances', models.TextField(help_text='Circumstances of disappearance')),
                ('reporter_name', models.CharField(max_length=200)),
                ('reporter_relationship', models.CharField(help_text='Relationship to missing person', max_length=100)),
                ('reporter_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('reporter_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('found', 'Found'), ('investigating', 'Under Investigation'), ('closed', 'Case Closed')], default='missing', max_length=20)),
                ('case_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('police_notified', models.BooleanField(default=False)),
                ('police_case_number', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Missing Person Report',
                'verbose_name_plural': 'Missing Person Reports',
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighting_date', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Description of the sighting')),
                ('witness_name', models.CharField(blank=True, max_length=200)),
                ('witness_contact', models.CharField(blank=True, max_length=15)),
                ('verified', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='reports.missingpersonreport')),
            ],
            options={
                'ordering': ['-sighting_date'],
            },
        ),
    ]
